### PR TITLE
merge fix from demo to master

### PR DESCRIPTION
**Pull request by wslack**

### CODE REVIEW

**Comment by wslack** [comment]
Build failed. I messed something up.

**Comment by wslack** [comment]
@el-mapache either we can try to fix this PR (I screwed up something in my merge commit). 

However, I can't open a PR from `master` to `demo` because that will break the site again

**Comment by wslack** [comment]
so I think options are:

1. PR straight to master
2. Bring demo up to date with master

WDYT?

**Comment by el-mapache** [comment]
@wslack We should open a new PR into master, with a branch based from demo, working on that now!

**Pull request closed without merging**
