### PR TITLE
additional updates to Threat based whitepaper

### PR DESCRIPTION
**Pull request by SaraLHerbst**

### CODE REVIEW

**Comment by SaraLHerbst** [comment]
@jthalls @mesilber please see the entry and downloadable file for review https://demo.fedramp.gov/documents-templates/

**Comment by mesilber** [comment]
@jthalls I'll let you confirm that it's the correct version, but the link works for me.

**Review by jthalls — APPROVED** [review]
Looks good and reflective of the upates. Please merge.

**Comment by SaraLHerbst** [comment]
@jthalls @mesilber done

**Pull request merged**
